#!/usr/bin/env python3
"""fa_bwd_compare.py —— FA 反向「ours vs ref vs FA vs TE」数值对拍汇总（P3-3）。

背景（ROADMAP P3-3）：把散落在各 dtype 文档/`*.out.txt` 里的数值对拍收敛成
**一个可复现的 harness**，作为 `docs/04-numerics-and-perf-summary.md` 数值表的唯一来源。

用法（宿主机直接跑，只需 numpy；dump 目录在本机可直接读）：
  python harness/fa_bwd_compare.py                       # 扫描全部 case
  python harness/fa_bwd_compare.py --dtype fp8           # 只看 fp8
  python harness/fa_bwd_compare.py --glob 'b1_s*_fp16'   # 按 slug 过滤
  python harness/fa_bwd_compare.py --case b1_s512_h16_d128_causal_fp16
  python harness/fa_bwd_compare.py --markdown            # 输出 markdown 表（贴文档）
  python harness/fa_bwd_compare.py --doc-table           # 输出 docs/04 可直接内联的分组表
  python harness/fa_bwd_compare.py --check docs/04-...md # 校验 docs/04 内嵌块是否为最新（CI 用，非零退出）
  python harness/fa_bwd_compare.py --apply docs/04-...md # 用最新实测**原地改写** docs/04 内嵌块
  python harness/fa_bwd_compare.py --out /tmp/cmp.txt     # 落盘

P3-3e：`--apply` / `--check` 操作 docs/04 里被下面两个标记围起来的自动生成块
（`<!-- BEGIN:auto-doc-table ... -->` … `<!-- END:auto-doc-table -->`）。`--apply` 把实测分组表
写回该块，`--check` 只做 diff 校验（块与实测不一致时打印 unified diff 并以退出码 1 结束）。
这样文档里的数值表不再靠人工誊抄——每次跑完 harness 用一条命令即可同步/校验。

口径：
  * baseline = `ref_{dq,dk,dv}.npy`（PyTorch fp32 autograd，见 fa_bwd_bench.py dump）；
  * 被比较实现 = 每个 case 目录里存在的 `<impl>_{dq,dk,dv}.npy`，impl ∈ {fa, te, ours, ...}；
  * `ours_*` 由我们的 kernel 以 `--dump=ours` 生成（fp16/bf16/fp8 × 单文件/两文件 host 均支持）；
  * max_abs = max|a-b|；max_rel = max(|a-b| / (|b| + 1e-3))（与 kernel 内 `diff_stat` 一致，
    近零元素会被放大，仅作参考，判据用 max_abs）；
  * 所有数组按 C-order flatten 后逐元素比较（varlen 的 packed [T,H,D] 天然适用）。
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

import numpy as np

OUT_ROOT = Path("/home/xieminglin/proj/output/fa-bwd")
VEC = ("dq", "dk", "dv")
IMPL_ORDER = ("fa3", "fa", "te", "ours")


def maxdiff(a: np.ndarray, b: np.ndarray):
    a = a.reshape(-1).astype(np.float64)
    b = b.reshape(-1).astype(np.float64)
    if a.shape != b.shape:
        raise ValueError(f"shape mismatch: {a.shape} vs {b.shape}")
    d = np.abs(a - b)
    r = d / (np.abs(b) + 1e-3)
    return float(d.max()), float(r.max())


def load(case: Path, name: str):
    p = case / f"{name}.npy"
    if not p.exists():
        return None
    return np.load(p)


def discover(args):
    cases = sorted(p for p in OUT_ROOT.iterdir() if p.is_dir())
    out = []
    for c in cases:
        if args.case and c.name not in args.case:
            continue
        import fnmatch
        if args.glob and not any(fnmatch.fnmatch(c.name, g) for g in args.glob):
            continue
        meta = {}
        mp = c / "meta.json"
        if mp.exists():
            meta = json.loads(mp.read_text())
        dt = meta.get("dtype", "")
        if args.dtype and dt not in args.dtype:
            continue
        out.append((c, meta))
    return out


def impl_of(case: Path):
    found = []
    for impl in IMPL_ORDER:
        if (case / f"{impl}_dq.npy").exists():
            found.append(impl)
    # 目录里其它可能的 <impl>_dq.npy（自定义前缀）也纳入，放在 ours 之后
    for p in sorted(case.glob("*_dq.npy")):
        impl = p.name[: -len("_dq.npy")]
        if impl not in found and impl != "ref":
            found.append(impl)
    return found


def fmt(v):
    return "  NA  " if v is None else f"{v:.3e}"


# ---- P3-3d：docs/04 可内联的分组表 ------------------------------------------
DT_ORDER = ("fp16", "bf16", "fp8")
FAM_ORDER = ("MHA", "GQA/MQA", "MLA", "varlen")
IMPL_LABEL = {
    "fa3": "FA3.0.0", "fa": "FA2.7.4", "te": "TE2.14",
    "ours": "**ours（两文件）**", "ours_sf": "ours（单文件）",
}

# P3-3e：docs/04 内嵌自动块的分隔标记。`--apply` / `--check` 只动这两个标记之间的内容。
MARK_BEGIN = "<!-- BEGIN:auto-doc-table (generated by harness/fa_bwd_compare.py --doc-table; do not edit by hand) -->"
MARK_END = "<!-- END:auto-doc-table -->"


def family(meta):
    if meta.get("varlen"):
        return "varlen"
    D = meta.get("D")
    if D and int(D) != 128:
        return "MLA"
    H, kv = meta.get("H"), meta.get("Hkv")
    if H and kv and int(kv) != int(H):
        return "GQA/MQA"
    return "MHA"


def shape_str(meta):
    """把 meta 渲染成一行紧凑 shape 描述（与 docs/04 §1/§7 的写法一致）。"""
    if meta.get("varlen"):
        lengths = meta.get("lengths", [])
        ls = ",".join(str(x) for x in lengths[:4]) + ("..." if len(lengths) > 4 else "")
        s = (f"varlen B={len(lengths)} T={meta.get('T')} [{ls}]"
             f" H={meta.get('H')} D={meta.get('D')}")
    else:
        s = f"({meta.get('B')},{meta.get('S')},{meta.get('H')},{meta.get('D')})"
    H, kv = meta.get("H"), meta.get("Hkv")
    if H and kv and int(kv) != int(H):
        s += f" Hkv={kv}"
    D, Dv = meta.get("D"), meta.get("Dv")
    if D and Dv and int(Dv) != int(D):
        s += f" Dv={Dv}"
    s += " " + ("causal" if meta.get("causal", True) else "full")
    return s


def doc_tables(rows, impl_filter=None):
    """把已算好的 (case, meta, impl, stats) 渲染成按 dtype × 家族分组的 markdown。

    每一行是一个 impl；同一 case 的首行带 shape、后续行留空，便于阅读。判据用 max_abs
    （baseline = fp32 ref），与 docs/04 §1/§7 相同。
    """
    by_dt = {}
    for name, meta, impl, st in rows:
        if impl_filter and impl not in impl_filter:
            continue
        by_dt.setdefault(meta.get("dtype", "?"), []).append((name, meta, impl, st))

    out = ["<!-- generated by harness/fa_bwd_compare.py --doc-table; "
           "baseline = fp32 ref, values = max_abs -->"]
    for dt in [d for d in DT_ORDER if d in by_dt] + sorted(set(by_dt) - set(DT_ORDER)):
        out.append("")
        out.append(f"### {dt}")
        groups = {}
        for name, meta, impl, st in by_dt[dt]:
            groups.setdefault(family(meta), []).append((name, meta, impl, st))
        for fam in [f for f in FAM_ORDER if f in groups] + sorted(set(groups) - set(FAM_ORDER)):
            out.append("")
            out.append(f"**{fam}**")
            out.append("")
            out.append("| shape | impl | dq max_abs | dk max_abs | dv max_abs |")
            out.append("|---|---|---|---|---|")
            def _key(item):
                _, m, _, _ = item
                return (0 if m.get("causal", True) else 1,
                        int(m.get("S") or m.get("T") or 0),
                        int(m.get("B") or 0), int(m.get("H") or 0), item[0])
            seen = set()
            for name, meta, impl, st in sorted(groups[fam], key=_key):
                label = IMPL_LABEL.get(impl, impl)
                shp = shape_str(meta) if name not in seen else ""
                seen.add(name)
                out.append(f"| {shp} | {label} | "
                           + " | ".join(f"{st[v][0]:.3e}" for v in VEC) + " |")
    return out


def doc_block(rows, impl_filter=None):
    """生成夹在 MARK_BEGIN/MARK_END 之间的完整块（含两行标记）。

    MARK_BEGIN 本身已含 provenance 注释，故去掉 `doc_tables` 的首行重复注释。
    """
    body = [ln for ln in doc_tables(rows, impl_filter) if not ln.startswith("<!-- generated")]
    return [MARK_BEGIN, *body, MARK_END]


def _extract_block(path: Path):
    lines = path.read_text().splitlines()
    try:
        b = lines.index(MARK_BEGIN)
    except ValueError:
        raise SystemExit(f"[--apply/--check] 未在 {path} 找到起始标记：{MARK_BEGIN}")
    try:
        e = lines.index(MARK_END, b + 1)
    except ValueError:
        raise SystemExit(f"[--apply/--check] 未在 {path} 找到结束标记：{MARK_END}")
    return lines, b, e


# 表格行里的浮点（科学计数）。用于「容差等价」比较：fp8 的 dK/dV 走跨 CTA atomicAdd，
# 每次运行的末位会抖动（如 7.108e-1 ↔ 7.107e-1）；文档同步不应被这种原子次序噪声触发。
_NUM_RE = re.compile(r"[-+]?\d+\.\d+[eE][-+]?\d+")


def _num_close(x, y, rtol, atol=1e-12):
    return abs(x - y) <= atol + rtol * max(abs(x), abs(y))


def block_equivalent(cur, exp, rtol):
    """结构逐行相同、且数值在 rtol 内 ⇒ 视为等价（不要求逐位）。返回 (ok, msg)。"""
    if len(cur) != len(exp):
        return False, f"行数不同（当前 {len(cur)} vs 期望 {len(exp)}）"
    for i, (a, b) in enumerate(zip(cur, exp)):
        if a == b:
            continue
        ta, tb = _NUM_RE.split(a), _NUM_RE.split(b)
        if ta != tb:
            return False, f"第 {i} 行结构不同：\n  current : {a}\n  expected: {b}"
        na = [float(x) for x in _NUM_RE.findall(a)]
        nb = [float(x) for x in _NUM_RE.findall(b)]
        if len(na) != len(nb) or not all(_num_close(x, y, rtol) for x, y in zip(na, nb)):
            return False, (f"第 {i} 行数值超出 rtol={rtol:g}：\n"
                           f"  current : {a}\n  expected: {b}")
    return True, ""


def apply_block(path: Path, block_lines, rtol):
    """把 block_lines 写回 path 的标记块；返回 (changed, diff_text)。

    若现有块与新块**容差等价**（原子次序噪声）则不改写，保持文档稳定。
    """
    lines, b, e = _extract_block(path)
    old = lines[b:e + 1]
    ok, _ = block_equivalent(old, list(block_lines), rtol)
    if ok:
        return False, ""
    diff = list(difflib.unified_diff(old, list(block_lines),
                                     fromfile=f"{path}:current", tofile=f"{path}:expected",
                                     lineterm=""))
    path.write_text("\n".join(lines[:b] + list(block_lines) + lines[e + 1:]) + "\n")
    return True, "\n".join(diff)


def consistency_report(rows_meta, ca, cb, ctol):
    """P3-3f：单文件 vs 两文件（或任意两个 impl）的实现一致性报告。

    同一算法的两种文件形态（device 代码逐字同源）唯一的期望差异来自跨 CTA
    `atomicAdd` 的求和次序（fp32 ulp 级）。本报告逐 case 给出 `max|A-B|`，并按 dtype
    汇总最大值；可选用 `--ctol` 让超过容差时以非零退出码报错（CI 回归门）。

    返回 (lines, worst, n_cases, n_missing)。
    """
    lines = []
    lines.append(f"=== fa-bwd 实现一致性（P3-3f）：{ca} vs {cb}（max_abs，逐元素）===")
    lines.append(f"baseline-free：两者都算同一数学；期望差异仅跨 CTA atomicAdd 次序（fp32 ulp）。")
    if ctol is not None:
        lines.append(f"判据：max|{ca}-{cb}| <= --ctol={ctol:g}（超出则退出码 1）")
    lines.append("")
    by_dt = {}
    n_cases = n_missing = 0
    worst = {v: (0.0, "") for v in VEC}
    for case, meta in rows_meta:
        dt = meta.get("dtype", "?")
        have = all((case / f"{ca}_{v}.npy").exists() and (case / f"{cb}_{v}.npy").exists()
                   for v in VEC)
        if not have:
            n_missing += 1
            by_dt.setdefault(dt, []).append((case.name, None))
            continue
        n_cases += 1
        st = {}
        for v in VEC:
            st[v] = maxdiff(load(case, f"{cb}_{v}"), load(case, f"{ca}_{v}"))[0]
            if st[v] > worst[v][0]:
                worst[v] = (st[v], case.name)
        by_dt.setdefault(dt, []).append((case.name, st))
    for dt in [d for d in DT_ORDER if d in by_dt] + sorted(set(by_dt) - set(DT_ORDER)):
        lines.append(f"[{dt}]")
        for name, st in sorted(by_dt[dt]):
            if st is None:
                lines.append(f"  {name:<46}  (缺 {ca} 或 {cb}，跳过)")
            else:
                lines.append(f"  {name:<46}  dq={st['dq']:.3e}  dk={st['dk']:.3e}  "
                             f"dv={st['dv']:.3e}")
        lines.append("")
    lines.append(f"=== 小结（{n_cases} case 有 {ca}/{cb} 双方；{n_missing} case 缺一侧）===")
    for v in VEC:
        d, who = worst[v]
        lines.append(f"  max|{ca}-{cb}| over all cases: {v} = {d:.3e}  ({who})")
    lines.append(f"  worst = {max(worst[v][0] for v in VEC):.3e}")
    return lines, max(worst[v][0] for v in VEC), n_cases, n_missing


def main():
    ap = argparse.ArgumentParser(description="fa-bwd numeric comparison (ours vs ref vs FA/TE)")
    ap.add_argument("--dtype", nargs="+", default=None, help="过滤 dtype：fp16/bf16/fp8")
    ap.add_argument("--glob", nargs="+", default=None, help="按 case slug 通配过滤")
    ap.add_argument("--case", nargs="+", default=None, help="精确 case 名称（可多个）")
    ap.add_argument("--impls", nargs="+", default=None, help="只报这些 impl（默认自动发现）")
    ap.add_argument("--markdown", action="store_true", help="输出 markdown 表格")
    ap.add_argument("--doc-table", action="store_true",
                    help="输出 docs/04 可直接内联的按 dtype×家族分组表（P3-3d）")
    ap.add_argument("--apply", default=None, metavar="DOC_MD",
                    help="用最新实测**原地改写** DOC_MD 里的 auto-doc-table 标记块（P3-3e）")
    ap.add_argument("--check", default=None, metavar="DOC_MD",
                    help="校验 DOC_MD 的 auto-doc-table 标记块是否为最新；不一致则打印 diff 并退出码 1")
    ap.add_argument("--rtol", type=float, default=5e-3,
                    help="--apply/--check 的数值容差（原子次序噪声；默认 5e-3）")
    ap.add_argument("--consistency", action="store_true",
                    help="P3-3f：报告两个 impl（默认 ours vs ours_sf）的逐 case 一致性")
    ap.add_argument("--ca", default="ours", help="--consistency 的 A 侧 impl（默认 ours）")
    ap.add_argument("--cb", default="ours_sf", help="--consistency 的 B 侧 impl（默认 ours_sf）")
    ap.add_argument("--ctol", type=float, default=None,
                    help="--consistency：max|A-B| 超过该值时退出码 1（默认只报不判）")
    ap.add_argument("--out", default=None, help="把结果同时写到文件")
    args = ap.parse_args()
    if args.apply or args.check:
        args.doc_table = True
        if args.apply and args.check:
            ap.error("--apply 与 --check 不能同时使用")

    if args.consistency:
        lines, worst, n_cases, n_missing = consistency_report(
            discover(args), args.ca, args.cb, args.ctol)
        text = "\n".join(lines)
        print(text)
        if args.out:
            Path(args.out).write_text(text + "\n")
            print(f"\n[written] {args.out}")
        if args.ctol is not None and worst > args.ctol:
            print(f"[--consistency] FAIL：worst={worst:.3e} > ctol={args.ctol:g}",
                  file=sys.stderr)
            return 1
        return 0

    rows = []   # (case, meta, impl, {vec: (abs, rel)})
    for case, meta in discover(args):
        ref = {v: load(case, f"ref_{v}") for v in VEC}
        if any(x is None for x in ref.values()):
            continue
        impls = impl_of(case)
        if args.impls:
            impls = [i for i in impls if i in args.impls]
        if not impls:
            continue
        for impl in impls:
            stats = {}
            ok = True
            for v in VEC:
                a = load(case, f"{impl}_{v}")
                if a is None:
                    ok = False
                    break
                stats[v] = maxdiff(a, ref[v])
            if ok:
                rows.append((case.name, meta, impl, stats))

    lines = []
    if args.doc_table:
        # 默认不重复列单文件版（ours_sf），要列就显式 --impls ours_sf。
        # FA 基线用 FA3（SM90，当前口径；fa2.7.4 可显式 --impls fa）。
        impl_filter = args.impls if args.impls else ("fa3", "te", "ours")
        block = doc_block(rows, impl_filter)
        if args.check:
            path = Path(args.check)
            cur_lines, b, e = _extract_block(path)
            cur = cur_lines[b:e + 1]
            ok, msg = block_equivalent(cur, block, args.rtol)
            if ok:
                print(f"[--check] OK：{path} 的 auto-doc-table 块与实测一致"
                      f"（{len(block)} 行，rtol={args.rtol:g}）")
                return 0
            diff = difflib.unified_diff(cur, block,
                                        fromfile=f"{path}:current", tofile=f"{path}: expected",
                                        lineterm="")
            print(f"[--check] STALE：{path} 的 auto-doc-table 块与实测不一致（{msg}），"
                  f"请运行 --apply 同步：\n")
            print("\n".join(diff))
            return 1
        if args.apply:
            path = Path(args.apply)
            changed, diff = apply_block(path, block, args.rtol)
            if changed:
                print(f"[--apply] 已更新 {path} 的 auto-doc-table 块（{len(block)} 行）")
                print(diff)
            else:
                print(f"[--apply] {path} 在 rtol={args.rtol:g} 内已是最新，无需修改"
                      f"（{len(block)} 行）")
            return 0
        lines = list(block)
    elif args.markdown:
        lines.append("| case | dtype | impl | dq max_abs | dq max_rel | dk max_abs | dk max_rel | "
                     "dv max_abs | dv max_rel |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for name, meta, impl, st in rows:
            lines.append(f"| {name} | {meta.get('dtype','')} | {impl} | "
                         + " | ".join(f"{st[v][0]:.3e} | {st[v][1]:.3e}" for v in VEC) + " |")
    else:
        lines.append("=== fa-bwd numeric comparison (baseline = ref; max_abs / max_rel) ===")
        hdr = f"{'case':<46} {'impl':<5} " + " ".join(f"{v}_abs    {v}_rel   " for v in VEC)
        lines.append(hdr)
        lines.append("-" * len(hdr))
        last = None
        for name, meta, impl, st in rows:
            if name != last:
                lines.append(f"[{name}]  ({meta.get('dtype','')})")
                last = name
            cells = " ".join(f"{fmt(st[v][0])} {fmt(st[v][1])}" for v in VEC)
            lines.append(f"  {impl:<5} {cells}")

    if not args.doc_table:
        # 分组小结：每个 dtype 下的 ours-vs-ref
        lines.append("")
        lines.append("=== ours vs ref 小结（判据 max_abs）===")
        by_dt = {}
        for name, meta, impl, st in rows:
            if impl != "ours":
                continue
            by_dt.setdefault(meta.get("dtype", "?"), []).append((name, st))
        for dt in sorted(by_dt):
            for name, st in by_dt[dt]:
                lines.append(f"  {dt:5s} {name:<46} dq={st['dq'][0]:.3e} "
                             f"dk={st['dk'][0]:.3e} dv={st['dv'][0]:.3e}")

    text = "\n".join(lines)
    print(text)
    if args.out:
        Path(args.out).write_text(text + "\n")
        print(f"\n[written] {args.out}")


if __name__ == "__main__":
    raise SystemExit(main())
